info:
  app:
    name: config
    description: Config service

spring:
  application:
    name: config
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:native}
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/cloud

eureka:
  client:
    enabled: false

#eureka:
#  client:
#    service-url:
#      defaultZone: ${EUREKA_SERVER_URL:http://eureka_client:eureka_password@localhost:8761/eureka}

management:
  endpoints:
    web.exposure.include: "*"
  endpoint:
    health:
      show-details: always

server:
  port: ${PORT:8888}