spring:
  r2dbc:
    url: ${DB_URL:r2dbc:postgresql://localhost:5432/users}
    username: ${POSTGRES_USER:username}
    password: ${POSTGRES_PASSWORD:qwerty}
    driver-class-name: org.postgresql.Driver

  liquibase:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/users}
    user: ${POSTGRES_USER:username}
    password: ${POSTGRES_PASSWORD:qwerty}
    driver-class-name: org.postgresql.Driver

  security:
    jwt:
      secret: ${SECRET:aGZiYmtiYWllYmNpZWFpZWJsZWNldWNlY2xhZWNhaWJlbGNhZWN3Q0VCV0VXSUM=}
      access: ${ACCESS:1}
      refresh: ${REFRESH:24}

  cloud:
    config:
      enabled: false

eureka:
  client:
    enabled: false

management:
  endpoints:
    web.exposure.include: "*"
  endpoint:
    health:
      show-details: always