services:

  chat-postgres:
    container_name: chat-postgres
    image: postgres:16
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    volumes:
      - ./init_databases.sql:/docker-entrypoint-initdb.d/init_databases.sql
    profiles:
      - cloud
      - local

  chat-config:
    container_name: config
    image: config
    ports:
      - "8888:8888"
    build:
      context: config
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: native
#      EUREKA_SERVER_URL: http://eureka_client:eureka_password@chat-eureka:8761/eureka
      PORT: 8888

      POSTGRES_USER: username
      POSTGRES_PASSWORD: password

      FEED_DB_URL: jdbc:postgresql://chat-postgres:5435/feed

    profiles:
      - cloud

  feed:
    container_name: feed
    restart: always
    image: feed
    ports:
      - "8381:8381"
    build:
      context: feed
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: cloud
      PORT: 8381
    depends_on:
      - chat-postgres
      - chat-config
    profiles:
      - cloud