spring:

  r2dbc:
    url: ${USER_R2DBC_URL:r2dbc:postgresql://chat-postgres:5432/users}
    username: ${POSTGRES_USER:username}
    password: ${POSTGRES_PASSWORD:password}

  liquibase:
    enabled: true
    url: ${USER_DB_URL:jdbc:postgresql://chat-postgres:5432/users}
    user: ${POSTGRES_USER:username}
    password: ${POSTGRES_PASSWORD:password}

  security:
    jwt:
      secret: ${SECRET:aGZiYmtiYWllYmNpZWFpZWJsZWNldWNlY2xhZWNhaWJlbGNhZWN3Q0VCV0VXSUM=}
      access: ${ACCESS:1}
      refresh: ${REFRESH:24}


eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://chat-eureka:8761/eureka}


management:
  endpoints:
    web.exposure.include: "*"
  endpoint:
    health:
      show-details: always