info:
  app:
    name: Gateway
    description: Gateway service
  team:
    name: D2 team

spring:
  application:
    name: chat-gateway-cloud
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

server:
  port: ${PORT:8080}