info:
  app:
    name: Gateway
    description: Gateway service
  team:
    name: D2 team

spring:
  application:
    name: chat-gateway
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

server:
  api:
    prefix: ${API_PREFIX:/api}
  port: ${PORT:8080}