spring:
  config:
    import: configserver:${CONFIG_SERVER_URL:http://localhost:8888}/
  cloud:
    config:
      fail-fast: true
#      discovery:
#        enabled: true
#        service-id: afa-config