spring:
  application:
    name: eureka-server
server:
  port: ${SERVER_PORT:8761}
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}